# Generated by Django 3.0.6 on 2020-05-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yeonlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_addr', models.CharField(max_length=255)),
                ('dong_addr', models.CharField(max_length=255)),
                ('road_addr', models.CharField(max_length=255)),
                ('bldg_nm', models.CharField(max_length=255)),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=19)),
                ('base_area', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=19)),
                ('struct_name', models.CharField(max_length=255)),
                ('struct_others', models.CharField(max_length=255)),
                ('main_use', models.CharField(max_length=255)),
                ('other_use', models.CharField(max_length=255)),
                ('roof_name', models.CharField(max_length=255)),
                ('roof_others', models.CharField(max_length=255)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('above_floors', models.IntegerField()),
                ('under_floors', models.IntegerField()),
                ('passenger_elev', models.IntegerField()),
                ('emergency_elev', models.IntegerField()),
                ('land_price_m2', models.IntegerField()),
                ('area_usage', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('constr_date', models.CharField(max_length=255)),
                ('est_price_m2', models.IntegerField()),
                ('est_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
